version: '3.8'
services:
  finance-backend:
    build: ./backend
    container_name: finance-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:      
      - ./backend/.env